muhammadsammy/tailwindcss-classnames

- src/index.ts
Hi 👋🏻
Thank you for this amazing library. I've decided to give something back and I've created this small PR.
> feat: add css grid properties

- src/createFile.ts
- src/utils.ts
I noticed these were missing so I figured I would add them since they're sort of blocking me on my project. Do tell me if there's anything you would like changed!
> Opacity from theme and text opacity

- src/createFile.ts
- src/utils.ts
Apologies for the commits, they're a little all over the place unfortunately!
This PR should bring this project up to speed with tailwind 1.4 as far as I can tell on their release notes. (https://tailwindcss.com/docs/release-notes/) I started using tailwind like almost literally yesterday so I might have missed something here just like I did with my last PR. Those previous misses have been corrected here though.
I was a bit split on if I should have also added the theming abilities to the new properties but since most of them inherit from previous properties that were already hard-coded, I decided against it. Probably something to think about in the future though along with possibly building up a framework for retrieving keys and setting them in the template.
> Full 1.4 compatibility

- src/cli/utils/baseTemplateString.ts
- src/index.ts
> Add default export

- src/cli/utils/baseTemplateString.ts
Add TKey to the template so that TTailwindString can be used in objects.
> feat(types): add TKey

- package.json
Add a script to generate src/index.ts
> chore: add generate script

- src/index.ts
Update `src/index.ts` by running the generate script.
> chore: run generate script

- src/cli/GeneratedFileWriter.ts
- src/cli/utils/baseTemplateString.ts
- src/index.ts
Add support for the Typography plugin and its classes.
Closes #36
> feat(plugins): add typography plugin support

- src/cli/ClassesGenerator.ts
> add group prefix

- src/cli/ClassesGenerator.ts
This reverts commit 52f10eb13cce21eda24913fb4c8d0d624a363f17.
> Revert "fix: add group prefix (#55)"

- .github/workflows/release.yml
> Add a GitHub workflow for releasing to github and npm

- src/cli/lib/non-configurable/layout.ts
- src/cli/types/classes.ts
- src/index.ts
> feat: add `isolation` utilities

- src/cli/lib/non-configurable/layout.ts
- src/cli/types/classes.ts
- src/index.ts
> feat: add `box-decoration-break` utilities

- src/cli/core/ClassnamesGenerator.ts
- src/cli/core/TailwindConfigParser.ts
- src/cli/types/config.ts
> feat: support JIT engine mode

- src/cli/core/ClassnamesGenerator.ts
- src/cli/core/FileContentGenerator.ts
> fix: pseudoClasses formatted incorrectly with prefix

- .github/workflows/release.yml
> chore(ci): add steps to generate the lib types for every release

- src/cli/core/TailwindConfigParser.ts
Fixes #222 
Fixes #57 
Fixes #63 
Hi,
I would appreciate your review on this fix for a few issues as discussed.
In the absence of tests, I am not quite sure how to verify my changes - do you have any test cases that could be used?
For now I just tested it with the following tailwind config:
```javascript
const colors = require('tailwindcss/colors');
module.exports = {
theme: {
spacing: {
0.2: '0.05rem',
},
colors: {
...colors,
someColor: {
100: '#123123',
200: '#123123',
},
},
extend: {
spacing: {
0.1: '0.025rem',
},
width: {
someWidth: '500rem',
},
colors: {
red: {
5000: '#ff0000',
},
someColor: {
300: '#123123',
400: '#123123',
},
},
},
},
};
```
I checked the result for the existence of:
- `border-someColor-100`, `border-someColor-200`, `border-someColor-300`, `border-someColor-400` …
> fix: Fixed config parser issues leading to ignored theme.extend settings

- package.json
- src/cli/lib/defaultTailwindConfig.ts
- src/cli/lib/non-configurable/backgrounds.ts
- yarn.lock
> feat: add support for the new background origin utils

- src/cli/core/ClassnamesGenerator.ts
- src/cli/lib/defaultTailwindConfig.ts
> feat: add caret-color utilities

- src/cli/core/ClassnamesGenerator.ts
- src/index.ts
> fix: use correct prefix for ring-inset class

- src/cli/core/ClassnamesGenerator.ts
- src/cli/types/classes.ts
- src/index.ts
> fix: add basic group and peer helpers
